hl.on("hyprland.start", function()
	hl.exec_cmd("app2unit -t service /usr/lib/xdg-desktop-portal-hyprland")
	hl.exec_cmd("app2unit -t service pypr")
	-- hl.exec_cmd("app2unit -t service /usr/lib/polkit-kde-authentication-agent-1")
	-- hl.exec_cmd("app2unit -t service hyprpaper")
	-- hl.exec_cmd("app2unit wl-paste --type text --watch cliphist store")
	-- hl.exec_cmd("app2unit wl-paste --type image --watch cliphist store")
	hl.dispatch(hl.dsp.focus({ workspace = 1 }))
	hl.exec_cmd("uwsm finalize")
end)
